- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.Xmodmap:
    ~/.agignore:
    ~/.alias:
    ~/.ansible.cfg:
    ~/.bashrc:
    ~/.commonrc:
    ~/.config/kitty/kitty.conf:
    ~/.config/nvim: vim
    ~/.ctags:
    ~/.dunstrc:
    ~/.flake8:
    ~/.functions:
    ~/.gemrc:
    ~/.git-templates:
    ~/.gitconfig:
    ~/.gitignore:
    ~/.i3:
    ~/.konsole:
    ~/.pylintrc:
    ~/.terraformrc:
    ~/.tmux.conf:
    ~/.toprc:
    ~/.vim:
    ~/.vimrc:
    ~/.vrapperrc:
    ~/.zshrc:

- shell:
  # Install hack font
  - curl -L 'https://github.com/source-foundry/Hack/releases/download/v3.000/Hack-v3.000-ttf.zip' -o ~/.fonts/Hack-v3.000-ttf.zip
  - unzip ~/.fonts/Hack-v3.000-ttf.zip -d ~/.fonts/
  - mv -f ~/.fonts/ttf/* ~/.fonts/
  - rm -rf ~/.fonts/{ttf,Hack-v3.000-ttf.zip}
  - fc-cache

  # Get tpm
  - git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm || true

  # Get zsh plugins
  - git clone https://github.com/zsh-users/zsh-syntax-highlighting ~/.dotfiles/zsh/plugins/zsh-syntax-highlighting || true

  # Install asdf
  - git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.4.0 || true


