- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.Xmodmap:
    ~/.alias:
    ~/.bashrc:
    ~/.commonrc:
    ~/.dunstrc:
    ~/.flake8:
    ~/.gemrc:
    ~/.gitconfig:
    ~/.gitignore:
    ~/.i3:
    ~/.konsole:
    ~/.terraformrc:
    ~/.tmux.conf:
    ~/.toprc:
    ~/.vim:
    ~/.vimrc:
    ~/.vrapperrc:
    ~/.zshrc:

- shell:
  # Install hack font
  - curl -L 'https://github.com/source-foundry/Hack/releases/download/v3.000/Hack-v3.000-ttf.zip' -o ~/.fonts/Hack-v3.000-ttf.zip
  - unzip ~/.fonts/Hack-v3.000-ttf.zip -d ~/.fonts/
  - mv -f ~/.fonts/ttf/* ~/.fonts/
  - rm -rf ~/.fonts/{ttf,Hack-v3.000-ttf.zip}
  - fc-cache

