#!/usr/bin/env bash

GREEN=$(echo -en '\033[00;32m')
BLUE=$(echo -en '\033[00;34m')
RESTORE=$(echo -en '\033[0m')

main() {
    LOCAL_USER=$(git config --local user.name)
    LOCAL_MAIL=$(git config --local user.email)
    GLOBAL_USER=$(git config user.name)
    GLOBAL_MAIL=$(git config user.email)

    CURRENT_USER=${LOCAL_USER:-$GLOBAL_USER}
    CURRENT_MAIL=${LOCAL_MAIL:-$GLOBAL_MAIL}

    CREDENTIALS_FILE=".git/.validated_credentials"

    if [ -f $CREDENTIALS_FILE ]; then
        # Check if something changed
        VALIDATED_USER=$(cat $CREDENTIALS_FILE | head -n1)
        VALIDATED_MAIL=$(cat $CREDENTIALS_FILE | tail -n1)
        if [[ "$CURRENT_USER" != "$VALIDATED_USER" ]] || [[ "$CURRENT_MAIL" != "$VALIDATED_MAIL" ]]; then
            validate_credentials
        fi
    else
        validate_credentials
    fi

    exit 0
}

validate_credentials() {
    read -r -p "Working as ${GREEN}$CURRENT_USER${RESTORE}(${BLUE}$CURRENT_MAIL${RESTORE}). Is this correct? [y/N] " response
    case "$response" in
        [yY][eE][sS]|[yY])
            echo "$CURRENT_USER" > $CREDENTIALS_FILE
            echo "$CURRENT_MAIL" >> $CREDENTIALS_FILE
            ;;
        *)
            echo "Set local ${GREEN}user.name${RESTORE} and ${BLUE}user.email${RESTORE} with the correct values and try again."
            exit 1
            ;;
    esac
}

# Allow interactive hooks
exec < /dev/tty
main
