---
dotfiles_dir: ~/.dotfiles
dotfiles_list:
  - alias
  - bashrc
  - commonrc
  - gemrc
  - gitconfig
  - gitignore
  - i3
  - tmux.conf
  - toprc
  - vim
  - vimrc
  - vrapperrc
  - Xmodmap
  - zshrc
